force-app/main/default/objects/GPT_Key__mdt/GPT_Key__mdt.object-meta.xml
<CustomObject>
    <label>GPT Key</label>
    <pluralLabel>GPT Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/GPT_Key__mdt/fields/Context_Words__c.field-meta.xml
<CustomField>
    <fullName>Context_Words__c</fullName>
    <label>Context Words</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPT_Key__mdt/fields/Max_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Max_Tokens__c</fullName>
    <defaultValue>2048</defaultValue>
    <description>The maximum number of tokens to generate in the completion.

The token count of your prompt plus max_tokens cannot exceed the model&apos;s context length. Most models have a context length of 2048 tokens (except for the newest models, which support 4096).</description>
    <label>Max Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GPT_Key__mdt/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <defaultValue>0.6</defaultValue>
    <description>What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.

We generally recommend altering this or top_p but not both.</description>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GPT_Key__mdt/fields/Top_P__c.field-meta.xml
<CustomField>
    <fullName>Top_P__c</fullName>
    <defaultValue>0</defaultValue>
    <description>An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.

We generally recommend altering this or temperature but not both.</description>
    <label>Top_P</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GPTConfigurationUtils_Test.cls
@isTest
public with sharing class GPTConfigurationUtils_Test {

    /*
        GPTMetadata_Test
        Test that the creation of GPTMetadata results in the right values being stored
        **TODO: Fix this test method, CMT can't be created in tests and is test visible...
    */
    @isTest
    public static void GPTMetadata_Test(){
        GPTConfigurationUtils.saveGPTMetadata('key', 'contextWords',  '1', '2', '3');
        Test.startTest();
            GPT_Key__mdt gptkey = GPTConfigurationUtils.getGPTMetadata();
            GPTConfigurationUtils.saveGPTMetadata('', 'contextWords',  '1', '2', '3');
            gptkey = GPTConfigurationUtils.getGPTMetadata();
        Test.stopTest();

        // System.assertEquals('contextWords', gptkey.Context_Words__c);
        // System.assertEquals(1, gptkey.Max_Tokens__c);
        // System.assertEquals(2, gptkey.Temperature__c);
        // System.assertEquals(3, gptkey.Top_P__c);
    }
}